export const mockData = [
  {
    id: 1,
    name: "Treadmill XT-2000",
    price: 1999,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuE64izeXdzIaAUNvzSJ_JayaRQ42YTupixUr5uiE1fg&s",
    tags: ["cardio", "fitness", "home gym"],
    instaLink: "https://instagram.com/examplefitness",
    fbLink: "https://facebook.com/examplefitness",
    twitterLink: "https://twitter.com/examplefitness",
    description:
      "The Treadmill XT-2000 is the perfect addition to your home gym setup. With its sturdy build and advanced features, you can enjoy a smooth and efficient workout every time.",
    ratings: 4.5,
    category: "Equipment",
    new: true,
  },
  {
    id: 3,
    name: "Dumbbell Set - 20kg",
    price: 99,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQPmsOD2p5Cu08VYlvjyXoVigBQNftjK9sjXLLqwKv6A&s",
    tags: ["strength training", "home gym", "muscle building"],
    instaLink: "https://instagram.com/examplestrength",
    fbLink: "https://facebook.com/examplestrength",
    twitterLink: "https://twitter.com/examplestrength",
    description:
      "Our Dumbbell Set - 20kg is perfect for beginners and advanced users alike. With adjustable weights and ergonomic design, you can target different muscle groups with ease.",
    ratings: 4.7,
    category: "Equipment",
  },
  {
    id: 4,
    name: "Yoga Mat - Eco-Friendly",
    price: 29,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5WrZE3mQn_zc1Rrc5yQxaIycFWaxs71qrhFjW46w-xA&s",
    tags: ["yoga", "fitness", "exercise"],
    instaLink: "https://instagram.com/exampleyoga",
    fbLink: "https://facebook.com/exampleyoga",
    twitterLink: "https://twitter.com/exampleyoga",
    description:
      "Our Eco-Friendly Yoga Mat provides the perfect balance of comfort and support for your yoga practice. Made from natural materials, it's gentle on the environment and your body.",
    ratings: 4.6,
    category: "Equipment",
  },
  {
    id: 5,
    name: "BCAA Powder - Watermelon",
    price: 39,
    imageUrl: "https://m.media-amazon.com/images/I/719QdyVaEBL._AC_SL1500_.jpg",
    tags: ["bcaa", "supplements", "recovery"],
    instaLink: "https://instagram.com/examplebcaa",
    fbLink: "https://facebook.com/examplebcaa",
    twitterLink: "https://twitter.com/examplebcaa",
    description:
      "Our refreshing Watermelon BCAA Powder is designed to support muscle recovery and hydration during and after intense workouts. With a delicious taste and essential amino acids, it's the perfect supplement for fitness enthusiasts.",
    ratings: 4.9,
    category: "Supplements",
  },
  {
    id: 6,
    name: "Elliptical Trainer - Pro Series",
    price: 2499,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZKcgA1fPAQBI2-sj0xlOSzryoC9ZpO1TY-w4-Zb0JuQ&s",
    tags: ["cardio", "fitness", "home gym"],
    instaLink: "https://instagram.com/examplefitness",
    fbLink: "https://facebook.com/examplefitness",
    twitterLink: "https://twitter.com/examplefitness",
    description:
      "Our Pro Series Elliptical Trainer offers a low-impact, full-body workout with customizable resistance levels and built-in workout programs. Get ready to elevate your fitness routine with this premium machine.",
    ratings: 4.8,
    category: "Equipment",
  },
  {
    id: 7,
    name: "Creatine Monohydrate - Unflavored",
    price: 19,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaevHZ6XkahFwWiIxLhrrFRLrUu1SvEWqG1x28_jCtcQ&s",
    tags: ["creatine", "supplements", "muscle building"],
    instaLink: "https://instagram.com/examplecreatine",
    fbLink: "https://facebook.com/examplecreatine",
    twitterLink: "https://twitter.com/examplecreatine",
    description:
      "Our Unflavored Creatine Monohydrate is perfect for adding strength, power, and endurance to your workouts. Made with pure ingredients and no fillers, it's the ideal supplement for serious athletes.",
    ratings: 4.7,
    category: "Supplements",
  },
  {
    id: 8,
    name: "Adjustable Weight Bench",
    price: 149,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEvusY75aOXEz9McQTriHNag-wfnFulw15hjajhYuOKg&s",
    tags: ["strength training", "home gym", "muscle building"],
    instaLink: "https://instagram.com/examplestrength",
    fbLink: "https://facebook.com/examplestrength",
    twitterLink: "https://twitter.com/examplestrength",
    description:
      "Our Adjustable Weight Bench offers versatility and stability for a wide range of exercises. Whether you're lifting weights or doing bodyweight exercises, this bench will help you reach your fitness goals.",
    ratings: 4.6,
    category: "Equipment",
  },
  {
    id: 9,
    name: "Whey Protein Isolate - Vanilla",
    price: 59,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUuRC94TwH6rMPDa2Q6HGjmeIxF4KrL29Hqb6C1yUDeA&s",
    tags: ["protein", "supplements", "nutrition"],
    instaLink: "https://instagram.com/exampleprotein",
    fbLink: "https://facebook.com/exampleprotein",
    twitterLink: "https://twitter.com/exampleprotein",
    description:
      "Our Vanilla Whey Protein Isolate is the perfect post-workout recovery drink. With a smooth texture and delicious flavor, it's a convenient way to replenish your muscles and support muscle growth.",
    ratings: 4.9,
    category: "Supplements",
    new: true,
  },
  {
    id: 10,
    name: "Resistance Bands Set",
    price: 39,
    imageUrl:
      "https://fitfam.ie/wp-content/uploads/2022/02/HPYGN-Resistance-Bands-Set-min.png",
    tags: ["strength training", "home gym", "rehabilitation"],
    instaLink: "https://instagram.com/exampleresistance",
    fbLink: "https://facebook.com/exampleresistance",
    twitterLink: "https://twitter.com/exampleresistance",
    description:
      "Our Resistance Bands Set is designed to help you build strength, improve flexibility, and recover from injuries. With varying resistance levels and durable construction, it's perfect for all fitness levels.",
    ratings: 4.7,
    category: "Equipment",
  },
  {
    id: 11,
    name: "Omega-3 Fish Oil - 1000mg",
    price: 29,
    imageUrl:
      "https://i5.walmartimages.com/seo/Spring-Valley-Proactive-Support-Omega-3-from-Fish-Oil-Heart-General-Brain-Health-Dietary-Supplement-Softgels-1000-mg-120-Count_6518ee08-2b37-471b-aaa1-826e2bb74d68.5ef39bb1ae1fcb1bb3f2119e1202cdc7.jpeg",
    tags: ["supplements", "nutrition", "heart health"],
    instaLink: "https://instagram.com/exampleomega3",
    fbLink: "https://facebook.com/exampleomega3",
    twitterLink: "https://twitter.com/exampleomega3",
    description:
      "Our Omega-3 Fish Oil capsules provide essential fatty acids to support heart health, brain function, and joint mobility. Made from wild-caught fish and third-party tested for purity.",
    ratings: 4.8,
    category: "Supplements",
    new: true,
  },
  {
    id: 12,
    name: "Adjustable Dumbbells - 40kg",
    price: 299,
    imageUrl:
      "https://gazimo.co.ke/wp-content/uploads/2023/12/FitRx-SmartBells-Set-Quick-Select-Adjustable-Dumbbells-5-52-5-lbs-Pair-Black_68745ffa-afdb-493a-a49f-ca3b857514d6.777753729e5cf337177c130648e9a631.webp",
    tags: ["strength training", "home gym", "muscle building"],
    instaLink: "https://instagram.com/examplestrength",
    fbLink: "https://facebook.com/examplestrength",
    twitterLink: "https://twitter.com/examplestrength",
    description:
      "Our Adjustable Dumbbells - 40kg are perfect for serious lifters looking to maximize their strength gains. With adjustable weight settings and durable construction, they're built to last through even the toughest workouts.",
    ratings: 4.9,
    category: "Equipment",
  },
  {
    id: 13,
    name: "Casein Protein Powder - Chocolate",
    price: 39,
    imageUrl:
      "https://www.healthyu.co.ke/wp-content/uploads/2019/11/OPTIMUM-NUTRITION-GOLD-STANDARD-100-CASEIN-CREAMY-VANILLA-2LBS-909G-768x768.jpg",
    tags: ["protein", "supplements", "nutrition"],
    instaLink: "https://instagram.com/exampleprotein",
    fbLink: "https://facebook.com/exampleprotein",
    twitterLink: "https://twitter.com/exampleprotein",
    description:
      "Our Chocolate Casein Protein Powder is designed to support muscle recovery and growth during sleep. Made with slow-digesting protein and essential amino acids, it's the perfect bedtime snack for athletes.",
    ratings: 4.7,
    category: "Supplements",
    new: true,
  },
  {
    id: 14,
    name: "Rowing Machine - Pro Series",
    price: 999,
    imageUrl:
      "https://wersports.com/cdn/shop/articles/motivated-black-sportsman-having-workout-on-rowing_1200x800.jpg?v=1621257445",
    tags: ["cardio", "fitness", "home gym"],
    instaLink: "https://instagram.com/examplefitness",
    fbLink: "https://facebook.com/examplefitness",
    twitterLink: "https://twitter.com/examplefitness",
    description:
      "Our Pro Series Rowing Machine offers a full-body workout with adjustable resistance levels and a smooth rowing motion. Get ready to take your fitness to the next level with this premium machine.",
    ratings: 4.8,
    category: "Equipment",
  },
  {
    id: 15,
    name: "Branched-Chain Amino Acids - Fruit Punch",
    price: 29,
    imageUrl:
      "https://www.drivennutrition.net/cdn/shop/files/Amino_3D_FruitPunch_front_1.jpg?v=1695656112",
    tags: ["bcaa", "supplements", "recovery"],
    instaLink: "https://instagram.com/examplebcaa",
    fbLink: "https://facebook.com/examplebcaa",
    twitterLink: "https://twitter.com/examplebcaa",
    description:
      "Our Fruit Punch BCAA Powder is formulated to support muscle recovery and hydration during and after workouts. With a delicious taste and essential amino acids, it's the perfect supplement for athletes.",
    ratings: 4.9,
    category: "Supplements",
    new: true,
  },
  {
    id: 16,
    name: "Adjustable Weighted Vest - 20kg",
    price: 79,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVf94HZKyqnZ5v-GGP3Evt07bAOSeRARQj6WWpzKvdCg&s",
    tags: ["strength training", "home gym", "cardio"],
    instaLink: "https://instagram.com/examplestrength",
    fbLink: "https://facebook.com/examplestrength",
    twitterLink: "https://twitter.com/examplestrength",
    description:
      "Our Adjustable Weighted Vest - 20kg adds resistance to your workouts for increased intensity and calorie burn. With adjustable weight settings and a comfortable design, it's perfect for all fitness levels.",
    ratings: 4.7,
    category: "Equipment",
    new: true,
  },
  {
    id: 17,
    name: "Creatine Monohydrate - Fruit Punch",
    price: 19,
    imageUrl:
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs93258/y/8.jpg",
    tags: ["creatine", "supplements", "muscle building"],
    instaLink: "https://instagram.com/examplecreatine",
    fbLink: "https://facebook.com/examplecreatine",
    twitterLink: "https://twitter.com/examplecreatine",
    description:
      "Our Fruit Punch Creatine Monohydrate is designed to enhance strength, power, and endurance for improved athletic performance. Made with high-quality ingredients and no fillers.",
    ratings: 4.7,
    category: "Supplements",
    new: true,
  },
  {
    id: 18,
    name: "Jump Rope - Speed Pro",
    price: 19,
    imageUrl:
      "https://crossrope.com.au/cdn/shop/products/speed-pro-le-set-1E-820px_1.jpg?v=1677508612",
    tags: ["cardio", "fitness", "home gym"],
    instaLink: "https://instagram.com/examplefitness",
    fbLink: "https://facebook.com/examplefitness",
    twitterLink: "https://twitter.com/examplefitness",
    description:
      "Our Speed Pro Jump Rope is designed for high-speed skipping with precision bearings and adjustable length. Perfect for cardio workouts and improving agility and coordination.",
    ratings: 4.6,
    category: "Equipment",
  },
  {
    id: 19,
    name: "BCAA Capsules - Raspberry Lemonade",
    price: 29,
    imageUrl: "https://m.media-amazon.com/images/I/51DGhWXyWGL._AC_.jpg",
    tags: ["bcaa", "supplements", "recovery"],
    instaLink: "https://instagram.com/examplebcaa",
    fbLink: "https://facebook.com/examplebcaa",
    twitterLink: "https://twitter.com/examplebcaa",
    description:
      "Our Raspberry Lemonade BCAA Capsules are convenient and easy to take on the go. Designed to support muscle recovery and hydration, they're perfect for busy athletes.",
    ratings: 4.8,
    category: "Supplements",
    new: true,
  },
  {
    id: 20,
    name: "Adjustable Kettlebell - 20kg",
    price: 79,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLZDIQGJ_B1wBvcAxX068o_dQsUVI32clR-fErVozCjA&s",
    tags: ["strength training", "home gym", "muscle building"],
    instaLink: "https://instagram.com/examplestrength",
    fbLink: "https://facebook.com/examplestrength",
    twitterLink: "https://twitter.com/examplestrength",
    description:
      "Our Adjustable Kettlebell - 20kg offers versatile training options with adjustable weight settings. Perfect for swings, squats, and other kettlebell exercises.",
    ratings: 4.7,
    category: "Equipment",
    new: true,
  },
];
